version: "3.8"


services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: 
      - .env
    ports: 
      - "5432:5432"
    networks:
      - my_network
  backend:
    build: ./backend
    container_name: backend_api
    restart: always
    env_file: 
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
    networks:
      - my_network

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
